### ISSUE TITLE
Stereo inference?

### ISSUE THREAD

**Issue by leoauri** [anira-project/anira#1]
Hi!

I'm considering using anira for a project. I see notes that stereo inference is not fully implemented yet. What's missing?

Thanks :) Leo

**Comment by faressc** [comment]
Hi Leo,
Thanks for reaching out. There are quite a few places in the code that need to be adapted to stereo/multichannel processing. These include the backend processors. I will have an in-depth look what needs to be done and report back.
Cheers
Fares

**Comment by leoauri** [comment]
Thanks Fares!

**Comment by faressc** [comment]
You’re welcome! One class that already supports multichannel mostly is the InferenceManager. Starting from there all other classes need to be adapted to multi channel processing in a similar way that are in the process or prepare callback. This includes the InferenceThread, InferenceThreadPool, SessionElement and default PrePostProcessor. The ThreadSafeStructs then need to be prepared with multichannel input and output buffers, getting their channel num from the inference config. If you plan on implementing this, let me know if you have further questions. Otherwise as I am currently focusing on the Bela implementation for the next release, it will take me some time to finish this.
Cheers!

**Comment by faressc** [comment]
Hi Leo,

We now have multichannel support. Feel free to check the develop branch for the latest changes. Just be aware that the Readme and usage guides are not fully updated. You can find an example stereo InferenceConfig (and model when you build with examples on) at this relative location `extras/desktop/models/model-pool/SimpleStereoGainConfig.h`. Let me know if you try it out and need some help!

Cheers!
Fares

**Comment by leoauri** [comment]
Thanks for the update :)
